#=========================== Filebeat inputs =============================
filebeat.inputs:
  # 收集nginx日志
  - type: log
    enabled: true
    paths:
      - /Users/mars/Desktop/access.log
    # 日志是json开启这个
    json.keys_under_root: true
    json.overwrite_keys: true
    json.add_error_key: true

#-------------------------- Redis output ------------------------------
output.redis:
  hosts: ["127.0.0.1:28080"]   #输出到redis的机器
  password: "MCm)@wFpS5mzt=@,"
  key: "nginx_logs"   #redis中日志数据的key值ֵ
  db: 0
  timeout: 5

